/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Desafio;

import static org.junit.Assert.assertEquals;

import java.util.List;

import org.junit.Test;

public class DesafioTest {
    @Test public void testSomeLibraryMethod() {
        Desafio classUnderTest = new Desafio();
        List<String> input = List.of("Aline zenon", "walter Azevedo", "lucas suzuki", "tatiana");
        List<String> output = List.of("Azevedo, Walter", "Suzuki, Lucas", "Tatiana", "Zenon, Aline");
        List<String> listOutput = classUnderTest.processaEntrada(input);
        assertEquals(output, listOutput);
    }
}
